services:
  - type: web
    name: umde-backend
    env: python
    branch: main
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: ENV
        value: production
      - key: PYTHONPATH
        value: backend
    workDir: backend
