# rule_registry.py
import importlib
import pkgutil
import inspect
from types import ModuleType
from typing import List, cast

from backend.app.rules.base import ValidationRule

RULE_MODULE_PATHS = [
    "backend.app.rules.autogenerated",
    "backend.app.rules.handwritten"
]

def discover_rules() -> List[ValidationRule]:
    discovered_rules: List[ValidationRule] = []

    for package in RULE_MODULE_PATHS:
        folder = package.replace(".", "/")
        for _, module_name, _ in pkgutil.iter_modules([folder]):
            if module_name == "base":
                continue
            try:
                module: ModuleType = importlib.import_module(f"{package}.{module_name}")
                for name, obj in inspect.getmembers(module, inspect.isclass):
                    cls = cast(type, obj)
                    if issubclass(cls, ValidationRule) and cls is not ValidationRule:
                        discovered_rules.append(cls())
                        print(f"[Info] Loaded rule class: {name}")
            except Exception as e:
                print(f"⚠️ Error importing {package}.{module_name}: {e}")

    return discovered_rules

# FUTURE: UI-Defined Rule Integration
# --------------------------------------------------
# In future versions, UMDE will support ingesting validation rules 
# defined via a user interface (UI). These rules may be stored in 
# a JSON/YAML format and translated into Python classes at runtime 
# or via background code generation pipelines.
#
# This system will:
# - Enable health plans to define custom rules through the platform
# - Assign rule metadata (layer, severity, dependencies) via config
# - Integrate seamlessly into the DAG execution engine
# - Avoid full redeploys for every rule change
#
# This approach will be phased in post-MVP to support no-code customization.

